name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read .node-version
        run: echo "NODE_VERSION=$(cat .node-version | cut -c 2-)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: yarn
      - name: Install Packages
        run: yarn --immutable

      - name: Run Linters
        run: yarn lint
