name: Vercel Deploy
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      vercelArgs:
        description: 'Vercel CLI args'
        required: true
        default: '--prod'

jobs:
  deploy:
    name: Deploy ${{ matrix.subsite }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - subsite: Home
            projectIdSecret: VERCEL_HOME_PROJECT_ID
          - subsite: Blog
            projectIdSecret: VERCEL_BLOG_PROJECT_ID
          - subsite: Slides
            projectIdSecret: VERCEL_SLIDES_PROJECT_ID
          - subsite: Meet
            projectIdSecret: VERCEL_MEET_PROJECT_ID
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: true

      - name: Clone blog submodule
        uses: actions/checkout@v7
        with:
          repository: daveallie/blog
          path: blog
          ssh-key: ${{ secrets.BLOG_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout blog submodule
        run: git submodule update --init blog

      - name: Clone slides submodule
        uses: actions/checkout@v7
        with:
          repository: daveallie/slides
          path: slides
          ssh-key: ${{ secrets.SLIDES_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout slides submodule
        run: git submodule update --init slides

      - name: Vercel Deploy - ${{ matrix.subsite }}
        uses: amondnet/vercel-action@v42.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          github-comment: false
          vercel-project-id: ${{ secrets[matrix.projectIdSecret] }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ github.event.inputs.vercelArgs || '--prod' }}
