name: Vercel Deploy
concurrency: unique-key-here

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      vercelArgs:
        description: 'Vercel CLI args'
        required: true
        default: '--prod'

jobs:
  deploy-home:
    env:
      VERCEL_ARGS: ${{ github.event.inputs.vercelArgs }}
    runs-on: ubuntu-latest
    steps:
      - name: Set VERCEL_ARGS environment variable
        if: env.VERCEL_ARGS == null
        run: echo "VERCEL_ARGS=--prod" >> $GITHUB_ENV
      - name: Test VERCEL_ARGS environment variable
        run: echo "VERCEL_ARGS=$VERCEL_ARGS"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Clone blog submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/blog
          path: blog
          ssh-key: ${{ secrets.BLOG_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout blog submodule
        run: git submodule update --init blog

      - name: Clone slides submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/slides
          path: slides
          ssh-key: ${{ secrets.SLIDES_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout slides submodule
        run: git submodule update --init slides

      - name: Vercel Deploy - Home
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          github-comment: false
          vercel-project-id: ${{ secrets.VERCEL_HOME_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ env.VERCEL_ARGS }}

  deploy-blog:
    env:
      VERCEL_ARGS: ${{ github.event.inputs.vercelArgs }}
    runs-on: ubuntu-latest
    steps:
      - name: Set VERCEL_ARGS environment variable
        if: env.VERCEL_ARGS == null
        run: echo "VERCEL_ARGS=--prod" >> $GITHUB_ENV
      - name: Test VERCEL_ARGS environment variable
        run: echo "VERCEL_ARGS=$VERCEL_ARGS"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Clone blog submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/blog
          path: blog
          ssh-key: ${{ secrets.BLOG_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout blog submodule
        run: git submodule update --init blog

      - name: Clone slides submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/slides
          path: slides
          ssh-key: ${{ secrets.SLIDES_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout slides submodule
        run: git submodule update --init slides

      - name: Vercel Deploy - Blog
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          github-comment: false
          vercel-project-id: ${{ secrets.VERCEL_BLOG_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ env.VERCEL_ARGS }}

  deploy-slides:
    env:
      VERCEL_ARGS: ${{ github.event.inputs.vercelArgs }}
    runs-on: ubuntu-latest
    steps:
      - name: Set VERCEL_ARGS environment variable
        if: env.VERCEL_ARGS == null
        run: echo "VERCEL_ARGS=--prod" >> $GITHUB_ENV
      - name: Test VERCEL_ARGS environment variable
        run: echo "VERCEL_ARGS=$VERCEL_ARGS"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Clone blog submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/blog
          path: blog
          ssh-key: ${{ secrets.BLOG_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout blog submodule
        run: git submodule update --init blog

      - name: Clone slides submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/slides
          path: slides
          ssh-key: ${{ secrets.SLIDES_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout slides submodule
        run: git submodule update --init slides

      - name: Vercel Deploy - Slides
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          github-comment: false
          vercel-project-id: ${{ secrets.VERCEL_SLIDES_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ env.VERCEL_ARGS }}

  deploy-meet:
    env:
      VERCEL_ARGS: ${{ github.event.inputs.vercelArgs }}
    runs-on: ubuntu-latest
    steps:
      - name: Set VERCEL_ARGS environment variable
        if: env.VERCEL_ARGS == null
        run: echo "VERCEL_ARGS=--prod" >> $GITHUB_ENV
      - name: Test VERCEL_ARGS environment variable
        run: echo "VERCEL_ARGS=$VERCEL_ARGS"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Clone blog submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/blog
          path: blog
          ssh-key: ${{ secrets.BLOG_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout blog submodule
        run: git submodule update --init blog

      - name: Clone slides submodule
        uses: actions/checkout@v5
        with:
          repository: daveallie/slides
          path: slides
          ssh-key: ${{ secrets.SLIDES_SUBMODULE_DEPLOY_KEY }}
          persist-credentials: true

      - name: checkout slides submodule
        run: git submodule update --init slides

      - name: Vercel Deploy - Meet
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          github-comment: false
          vercel-project-id: ${{ secrets.VERCEL_MEET_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ env.VERCEL_ARGS }}
