name: Vercel Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
          # vercel-args: # optional, default is 
          github-comment: false
          vercel-project-name: davealliedotcom

